namespace Manifracture
{
    public enum BinaryControls
    {
        // Reserved
        None = 0,

        // Keyboard
        BackKey = 8,
        TabKey = 9,
        EnterKey = 13,
        PauseKey = 19,
        CapsLockKey = 20,
        KanaKey = 21,
        KanjiKey = 25,
        EscapeKey = 27,
        ImeConvertKey = 28,
        ImeNoConvertKey = 29,
        SpaceKey = 32,
        PageUpKey = 33,
        PageDownKey = 34,
        EndKey = 35,
        HomeKey = 36,
        LeftKey = 37,
        UpKey = 38,
        RightKey = 39,
        DownKey = 40,
        SelectKey = 41,
        PrintKey = 42,
        ExecuteKey = 43,
        PrintScreenKey = 44,
        InsertKey = 45,
        DeleteKey = 46,
        HelpKey = 47,
        D0Key = 48,
        D1Key = 49,
        D2Key = 50,
        D3Key = 51,
        D4Key = 52,
        D5Key = 53,
        D6Key = 54,
        D7Key = 55,
        D8Key = 56,
        D9Key = 57,
        AKey = 65,
        BKey = 66,
        CKey = 67,
        DKey = 68,
        EKey = 69,
        FKey = 70,
        GKey = 71,
        HKey = 72,
        IKey = 73,
        JKey = 74,
        KKey = 75,
        LKey = 76,
        MKey = 77,
        NKey = 78,
        OKey = 79,
        PKey = 80,
        QKey = 81,
        RKey = 82,
        SKey = 83,
        TKey = 84,
        UKey = 85,
        VKey = 86,
        WKey = 87,
        XKey = 88,
        YKey = 89,
        ZKey = 90,
        LeftWindowsKey = 91,
        RightWindowsKey = 92,
        AppsKey = 93,
        SleepKey = 95,
        NumPad0Key = 96,
        NumPad1Key = 97,
        NumPad2Key = 98,
        NumPad3Key = 99,
        NumPad4Key = 100,
        NumPad5Key = 101,
        NumPad6Key = 102,
        NumPad7Key = 103,
        NumPad8Key = 104,
        NumPad9Key = 105,
        MultiplyKey = 106,
        AddKey = 107,
        SeparatorKey = 108,
        SubtractKey = 109,
        DecimalKey = 110,
        DivideKey = 111,
        F1Key = 112,
        F2Key = 113,
        F3Key = 114,
        F4Key = 115,
        F5Key = 116,
        F6Key = 117,
        F7Key = 118,
        F8Key = 119,
        F9Key = 120,
        F10Key = 121,
        F11Key = 122,
        F12Key = 123,
        F13Key = 124,
        F14Key = 125,
        F15Key = 126,
        F16Key = 127,
        F17Key = 128,
        F18Key = 129,
        F19Key = 130,
        F20Key = 131,
        F21Key = 132,
        F22Key = 133,
        F23Key = 134,
        F24Key = 135,
        NumLockKey = 144,
        ScrollKey = 145,
        LeftShiftKey = 160,
        RightShiftKey = 161,
        LeftControlKey = 162,
        RightControlKey = 163,
        LeftAltKey = 164,
        RightAltKey = 165,
        BrowserBackKey = 166,
        BrowserForwardKey = 167,
        BrowserRefreshKey = 168,
        BrowserStopKey = 169,
        BrowserSearchKey = 170,
        BrowserFavoritesKey = 171,
        BrowserHomeKey = 172,
        VolumeMuteKey = 173,
        VolumeDownKey = 174,
        VolumeUpKey = 175,
        MediaNextTrackKey = 176,
        MediaPreviousTrackKey = 177,
        MediaStopKey = 178,
        MediaPlayPauseKey = 179,
        LaunchMailKey = 180,
        SelectMediaKey = 181,
        LaunchApplication1Key = 182,
        LaunchApplication2Key = 183,
        OemSemicolonKey = 186,
        OemPlusKey = 187,
        OemCommaKey = 188,
        OemMinusKey = 189,
        OemPeriodKey = 190,
        OemQuestionKey = 191,
        OemTildeKey = 192,
        ChatPadGreenKey = 202,
        ChatPadOrangeKey = 203,
        OemOpenBracketsKey = 219,
        OemPipeKey = 220,
        OemCloseBracketsKey = 221,
        OemQuotesKey = 222,
        Oem8Key = 223,
        OemBackslashKey = 226,
        ProcessKeyKey = 229,
        OemCopyKey = 242,
        OemAutoKey = 243,
        OemEnlWKey = 244,
        AttnKey = 246,
        CrselKey = 247,
        ExselKey = 248,
        EraseEofKey = 249,
        PlayKey = 250,
        ZoomKey = 251,
        Pa1Key = 253,
        OemClearKey = 254,

        // Game pad
        DPadUpGamePad = 255,
        DPadDownGamePad = 256,
        DPadLeftGamePad = 257,
        DPadRightGamePad = 258,
        StartGamePad = 259,
        BackGamePad = 260,
        LeftStickGamePad = 261,
        RightStickGamePad = 262,
        LeftShoulderGamePad = 263,
        RightShoulderGamePad = 264,
        BigButtonGamePad = 266,
        AGamePad = 267,
        BGamePad = 268,
        XGamePad = 269,
        YGamePad = 270,
        LeftThumbstickLeftGamePad = 276,
        RightTriggerGamePad = 277,
        LeftTriggerGamePad = 278,
        RightThumbstickUpGamePad = 279,
        RightThumbstickDownGamePad = 280,
        RightThumbstickRightGamePad = 281,
        RightThumbstickLeftGamePad = 282,
        LeftThumbstickUpGamePad = 283,
        LeftThumbstickDownGamePad = 284,
        LeftThumbstickRightGamePad = 285,

        // Mouse
        LeftMouse = 286,
        MiddleMouse = 287,
        RightMouse = 288,
        XButton1Mouse = 289,
        XButton2Mouse = 290,
        ScrollWheelUp = 291,
        ScrollWheelDown = 292,
    }

    public enum HalfIntervalControls
    {
        LeftTriggerGamePad,
        RightTriggerGamePad,
        LeftThumbStickUpGamePad,
        LeftThumbStickDownGamePad,
        LeftThumbStickRightGamePad,
        LeftThumbStickLeftGamePad,
        RightThumbStickUpGamePad,
        RightThumbStickDownGamePad,
        RightThumbStickRightGamePad,
        RightThumbStickLeftGamePad,
        ScrollWheelMouse,
    }

    public enum FullIntervalControls
    {
        LeftThumbstickXGamePad,
        LeftThumbstickYGamePad,
        RightThumbstickXGamePad,
        RightThumbstickYGamePad,
        LeftAndRightTriggersGamepad,
    }

    public enum FullAxisControls
    {
        AnyMoveMouseX,
        AnyMoveMouseY,
        NoDragMoveMouseX,
        NoDragMoveMouseY,
        LeftDragMouseX,
        LeftDragMouseY,
        MiddleDragMouseX,
        MiddleDragMouseY,
        RightDragMouseX,
        RightDragMouseY,
        LeftOrRightDragMouseX,
        LeftOrRightDragMouseY,
        ScrollWheelMouse,
    }
}
